# ~/.config/starship.toml
[line_break]
disabled = true


# Remove the "❯" symbol in the prompt
[character]                     
success_symbol = " [](green)"       #No success_symbol
error_symbol = " [✗](bold red)" #error_symbol in red



[username]
#format = "[➜ ](red)[$user]($style)[@](cyan)"
format ="[❯](#BF616A)[❯](#02e830)[❯](#88C0D0)[❯](#EBCB8B) "
style_user = "#5fff5f"
show_always = true

#[[battery.display]]
#threshold = 30
#style = "bold red"

[cmd_duration]
min_time = 100_000  # Show command duration over 100,000 milliseconds
format = " took [$duration]($style)"
disabled = true

[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "

[hostname]
ssh_only = false
format = "[$hostname in]($style) "
trim_at = "-"
style = "#5fff5f"
disabled = true

[aws]
symbol = " "

[conda]
symbol = " "

[cmake]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

#[haskell]
#symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
show_percentage = true
#show_swap = true
#threshold = 70
#style = "bold dimmed white"
disabled = true

[time]
time_format = "%T"
format = "🕙 $time($style) "
style = "bright-white"
disabled = true


