#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xrandr --rate 144 &
xsetroot -cursor_name left_ptr &
lxpolkit &
picom --experimental-backends &
feh --bg-fill --randomize $HOME/Documents/nordic-wallpapers/wallpapers/* &
$HOME/.config/polybar/launch.sh &
if [[ ! -f "$HOME/.cache/eww_launch.xyz" ]]; then
  ./.config/scripts/loadEww
else 
  rm $HOME/.cache/eww_launch.xyz
  ./.config/scripts/loadEww
fi
xfce4-power-manager --no-daemon &
#polybar main &

bspc monitor -d I II III IV V 

bspc config border_width         2
bspc config window_gap           8
bspc config gapless_monocle false
bspc config borderless_monocle true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
#bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true
bspc config normal_border_color "#2E3340"
bspc config focused_border_color "#88C0D0"
bspc config pointer_motion_interval 7ms
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
